name: Docker_Build_Push_to_Azure_Container_Registry
on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
        default: "anuragpachauri434/backstage"
        
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
        default: "anuragpachauri434/backstage"

permissions:
  contents: read

jobs:
  Build:
    if: github.ref_type == 'tag' 
    runs-on: ubuntu-latest
    env:
      ENV: staging 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_NONPROD_PLATFORMENG_ACR_ENDPOINT }}
          username: ${{ secrets.AZURE_NONPROD_PLATFORMENG_ACR_USERNAME }}
          password: ${{ secrets.AZURE_NONPROD_PLATFORMENG_ACR_PASSWORD }}
           
      - name: Build & Push
        uses: docker/build-push-action@v5.3.0
        with:
          file: ./packages/backend/Dockerfile
          push: true
          build-args: |
            version=${{  github.ref_name }} 
            ENV=${{ env.ENV }}
          tags: |
            ${{ secrets.AZURE_NONPROD_PLATFORMENG_ACR_ENDPOINT }}/${{inputs.IMAGE_NAME}}:${{  github.ref_name }}
            ${{ secrets.AZURE_NONPROD_PLATFORMENG_ACR_ENDPOINT }}/${{inputs.IMAGE_NAME}}:latest

